# Generated by Django 3.2.3 on 2021-08-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_desc',
        ),
    ]
