# Generated by Django 3.2.3 on 2021-08-13 21:11

import datetime
from django.db import migrations
from django.utils.timezone import utc
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0002_remove_question_question_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_desc',
            field=djrichtextfield.models.RichTextField(default=datetime.datetime(2021, 8, 13, 21, 11, 38, 847234, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
