# Generated by Django 3.2.3 on 2021-08-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0004_alter_question_question_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
