# Generated by Django 3.2.3 on 2021-08-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nss_app', '0005_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
